pipeline:
  name: "Indian_ALPR_Pipeline_v1"
  device: "cpu"

vehicle_detection:
  model_type: "yolov8"
  weights_path: "ai/models/yolov8_vehicle.pt"
  confidence_threshold: 0.50
  allowed_classes: ["car", "truck", "bus", "motorbike"]

plate_detection:
  model_type: "yolov8_plate"
  weights_path: "ai/models/yolov8_plate.pt"
  confidence_threshold: 0.60

ocr:
  engine: "tesseract"
  language: "eng"
  psm_mode: 7
  target_format: "INDIAN_PLATE" # State Code + 2 Digits + 1/2 Letters + 4 Digits (e.g., RJ14AB1234)

postprocessing:
  clean_regex: "^[A-Z]{2}[0-9]{1,2}[A-Z]{1,3}[0-9]{4}$"
  min_character_length: 8
  max_character_length: 11
